DEBUG             = False
FEATURE_THRESHOLD = 0.01
DESCRIPTOR_SIZE   = 5
MATCHING_Y_RANGE  = 30

RANSAC_K              = 1000
RANSAC_THRES_DISTANCE = 3

ALPHA_BLEND_WINDOW = 2

FEATURE_CUT_X_EDGE = 10
FEATURE_CUT_Y_EDGE = 50
